-- Course     : 511783-001 Database Systems
-- Lab        : Lab 07: Normalization
-- Description: RUN-ONLY teaching seed. Student, Course, Instructor, and
--              Enrollment are clean and normalized. Section is
--              DELIBERATELY denormalized: it copies course_title and
--              instructor_name in directly, instead of only holding
--              course_code and instructor_id, and it declares no
--              foreign keys on those two columns at all. That missing
--              constraint is part of the lesson: nothing stops Section
--              from drifting out of sync with Course and Instructor, or
--              from naming a course or instructor that exists nowhere
--              else in the database.
--
-- Do not edit this file. Run it once, then work through Lab 07's
-- Guided Exercises using anomaly_triggers.sql.
--
-- Idempotent: safe to run from scratch, any number of times.

DROP DATABASE IF EXISTS registration_db;
CREATE DATABASE registration_db;
USE registration_db;

CREATE TABLE Student (
  student_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  major VARCHAR(100),
  CONSTRAINT pk_student PRIMARY KEY (student_id)
);

CREATE TABLE Course (
  course_code VARCHAR(10) NOT NULL,
  title VARCHAR(100) NOT NULL,
  CONSTRAINT pk_course PRIMARY KEY (course_code)
);

CREATE TABLE Instructor (
  instructor_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  CONSTRAINT pk_instructor PRIMARY KEY (instructor_id)
);

-- THE DENORMALIZED TABLE. course_title and instructor_name are copied
-- in directly. Notice there is no FOREIGN KEY on course_code or on
-- instructor_id: this table trusts whoever inserts a row to keep the
-- copies consistent with Course and Instructor by hand. Nobody enforces
-- it.
CREATE TABLE Section (
  section_id      INT NOT NULL,
  course_code     VARCHAR(10) NOT NULL,
  course_title    VARCHAR(100) NOT NULL,
  instructor_id   INT NOT NULL,
  instructor_name VARCHAR(100) NOT NULL,
  room            VARCHAR(20),
  semester        VARCHAR(20),
  CONSTRAINT pk_section PRIMARY KEY (section_id)
);

CREATE TABLE Enrollment (
  student_id INT NOT NULL,
  section_id INT NOT NULL,
  grade      VARCHAR(2),
  CONSTRAINT pk_enrollment PRIMARY KEY (student_id, section_id),
  CONSTRAINT fk_enrollment_student FOREIGN KEY (student_id)
    REFERENCES Student (student_id),
  CONSTRAINT fk_enrollment_section FOREIGN KEY (section_id)
    REFERENCES Section (section_id)
);

-- ---------------------------------------------------------------------
-- Data
-- ---------------------------------------------------------------------

INSERT INTO Student (student_id, name, major) VALUES
  (1, 'Kim Minji', 'Computer Science'),
  (2, 'Lee Jiho', 'Computer Science'),
  (3, 'Park Sooyoung', 'Mathematics');

-- Course and Instructor hold the CANONICAL data. Notice CS330 and
-- instructor_id 3 (Dr. Park) are missing from here on purpose — see
-- Section below.
INSERT INTO Course (course_code, title) VALUES
  ('CS101', 'Intro to Programming'),
  ('CS201', 'Database Systems');

INSERT INTO Instructor (instructor_id, name) VALUES
  (1, 'Prof. Kim'),
  (2, 'Prof. Lee');

-- Section 1: CS101, one section, matches Course/Instructor exactly.
-- Sections 2 and 3: CS201 has TWO sections, both taught by Prof. Lee
--   (instructor_id 2). The same fact, "instructor 2 is named Prof.
--   Lee", is now copied into two different rows. That redundancy is
--   the whole problem this lab hunts.
-- Section 4: CS330, "Operating Systems", taught by "Dr. Park"
--   (instructor_id 3). Neither CS330 nor instructor_id 3 has a row in
--   Course or Instructor — this single Section row is the ONLY place
--   in the entire database that either fact is recorded. That is what
--   makes it a live insertion/deletion-anomaly demo, not just a
--   hypothetical. It has no Enrollment rows either (its last student
--   already finished the course), so it can be deleted cleanly in
--   anomaly_triggers.sql without hitting a foreign-key error.
INSERT INTO Section
  (section_id, course_code, course_title, instructor_id, instructor_name, room, semester)
VALUES
  (1, 'CS101', 'Intro to Programming', 1, 'Prof. Kim', 'R101', '2026-2'),
  (2, 'CS201', 'Database Systems',     2, 'Prof. Lee', 'R203', '2026-2'),
  (3, 'CS201', 'Database Systems',     2, 'Prof. Lee', 'R204', '2026-2'),
  (4, 'CS330', 'Operating Systems',    3, 'Dr. Park',  'R110', '2026-2');

-- Note: no student is enrolled in section_id 4 (CS330) — that section
-- has already finished for the term, so it can be deleted cleanly in
-- the deletion-anomaly demo below without a foreign-key conflict.
INSERT INTO Enrollment (student_id, section_id, grade) VALUES
  (1, 1, 'A0'),
  (1, 2, 'B+'),
  (2, 2, 'A0'),
  (2, 1, 'B0'),
  (3, 1, 'B0');
